export const FILE_INPUT = document.getElementById('file_input') as HTMLInputElement;
export const PREVIEW_CANVAS = document.getElementById('prev_canvas') as HTMLCanvasElement;
export const IMG = document.getElementById('img')
export const PREVIEW_CANVAS_CONTEXT = PREVIEW_CANVAS.getContext('2d')!;
export const X_SIZE_INPUT = document.getElementById('x_size') as HTMLInputElement;
export const Y_SIZE_INPUT = document.getElementById('y_size') as HTMLInputElement;
export const FIELD = document.getElementById('field') as HTMLDivElement;
export const SHUFFLE_BUTTON = document.getElementById('shuffle') as HTMLButtonElement;
export const ANSWER_CANVAS = document.getElementById('answer') as HTMLCanvasElement;
